### PR TITLE
Update submodules

### PR DESCRIPTION
**Pull request by smattes**

### CODE REVIEW

**Comment by smattes** [comment]
Should we merge master into all the acceptance test failure case branches?

**Comment by caryncc** [comment]
I tried testing this branch on prod and it's throwing this error: 

2-7-2017, 12:40:51 PM
"TypeError: Cannot convert undefined or null to object"

**Comment by colemai** [comment]
This should be good to go now @caryncc. It was a cloudtrail error that I have a PR in for but also this runs fine if you run it with all four of the cloudtrail alerts - which is now the default so you could create a new plan and run that without issue

**Comment by caryncc** [comment]
Tested update-submodules branch on prod and it ran successfully. Woo!

**Pull request merged**
